
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: ./BACKEND
    env_file:
      - ./BACKEND/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./BACKEND:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
# # docker compose up -d 
# # psql -U myuser -d mydb